version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Database configuration - estas variables se pueden usar en lugar de hardcoding
      - DB_SERVER=securityorasystem.database.windows.net
      - DB_DATABASE=OrasystemSecurity
      - DB_USER=administrador
      - DB_PASSWORD=Admin123.
      - DB_PORT=1433
      - DB_ENCRYPT=true
      - DB_TRUST_SERVER_CERTIFICATE=true
    volumes:
      # Mount uploads directory for persistent file storage
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--timeout=8", "http://localhost:3001/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add database service if using local SQL Server
  # Uncomment and configure if needed
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=YourPassword123!
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqlserver_data:/var/opt/mssql

# volumes:
#   sqlserver_data: 